### ISSUE TITLE
Editor request: fix big spacing around code words

### ISSUE THREAD

**Issue by hadro** [mnyrop/iiifc-theme#25]

**Comment by mnyrop** [comment]
@hadro is this like `rights` at https://preview.iiif.io/api/wireframe/api/image/3.0/#56-rights ?
If so, there's spacing because the code words actually have a light grey background, which needs padding to show up. 

Options to remedy this include:
1. removing the background entirely, though this risks not differentiating code words from RFC words
2. making the code word backgrounds pop more, so they doesn't blend in with the body background
3. minimizing the amount of padding around the words
4. some combo of 2 & 3

Any thoughts?

**Comment by hadro** [comment]
Aha, you're right, I didn't notice the background (and I suspect the editors did not either) which is why it looks like there's so much padding.

Yes, I agree, I think it's a combo of 2 + 3.

**Comment by mnyrop** [comment]
@hadro sounds good. i will play around with some styles and add them to #32 so the editors can review along with the spec layout changes.
